#!/usr/bin/perl
use strict;
use Proviral qw(checkSource checkHost readSource);

my $numArg = scalar @ARGV;
if ($numArg < 1){
	print "No parameter given for type\n\n";
	&usage();
}

my $type = $ARGV[0];
unless ($type eq "host" || $type eq "virus"){
	print "The given type $type is not either host or virus\n\n";
	&usage();
}

my $residue = $numArg % 2;
if ($residue == 0){
	print "Wrong pair between source and its version\n\n";
	&usage();
}

my %source;
if ($numArg > 1){
	for (my $i = 1; $i < $numArg; $i+=2){
		$source{$ARGV[$i]} = $ARGV[$i+1];
	}
}else{
	%source = %{&readSource()};
}

&checkSource(\%source);
&checkHost();

open BAT, ">batchPopulate_$type.bat";

foreach my $source (keys %source){
	my $version = $source{$source}{version};
	my $dataFolder = "e:\\\\proviral\\\\datafiles\\\\$type\\\\$source\\\\$version";
	$dataFolder =~s/ /_/g;
	unless (-d $dataFolder){
		print "No data files found for data source $source with version $version\n";
		print "Please make sure that all files for that source should be kept under folder $dataFolder\n";
		next;
	}
	my $sqlFile = "sql-$type-$source-$version.sql";
	open OUT, ">$sqlFile";
	print OUT "#This sql file is generated by populateDatabase.pl for $type from data source $source with version $version\;\n";

	if($type eq "virus"){
		print OUT "load data local infile \'$dataFolder\\\\populate_virus_${type}_${source}_${version}.tsv\' into table proviral.virus;\n";
		print OUT "select concat (\"Insert \", row_count(), \" rows into virus table\") as ''\;\n";
		print OUT "load data local infile \'$dataFolder\\\\populate_infection_${type}_${source}_${version}.tsv\' into table proviral.infection\;\n";
		print OUT "select concat (\"Insert \", row_count(), \" rows into infection table\") as ''\;\n";
	}

	print OUT "load data local infile \'$dataFolder\\\\populate_protein_${type}_${source}_${version}.tsv\' into table proviral.protein\;\n";
	print OUT "select concat (row_count(), \" entries for protein from $type for $source $version\") as ''\;\n";

	print OUT "load data local infile \'$dataFolder\\\\populate_peptide_${type}_${source}_${version}.tsv\' into table proviral.peptide\;\n";
	print OUT "select concat (row_count(), \" entries for peptide from $type for $source $version\") as ''\;\n";

	print OUT "load data local infile \'$dataFolder\\\\populate_peptide_existance_${type}_${source}_${version}.tsv\' into table proviral.peptide_existance\;\n";
	print OUT "select concat (row_count(), \" rows into peptide_existance from $type for $source $version\") as ''\;\n";

	print OUT "#load data local infile \'$dataFolder\\\\populate_product_${type}_${source}_${version}.tsv\' into table proviral.product_ion\;\n";
	print OUT "#select concat (row_count(), \" rows into product_ion from $type for $source $version\") as ''\;\n";
	close OUT;

	print "SQL file $sqlFile has been generated for $source $version\n";
	print BAT "mysql -u proviral -pproviral < \"$sqlFile\"\n";
}

sub usage(){
	print "Usage: populateDatabase.pl <type> [<source 1> <version 1>] ... [<source n> <version n>]\n";
	print "type can be only either host or virus\n";
	print "The source file should be populate_source.tsv and the host file is populate_host.tsv both of which locate in the same folder as this program\n";
	print "If no source-version pair parameters provided, all sources contained in the source file will be processed\n";
	print "Otherwise, only given sources will be processed\n";
	exit 1;
}
